#!/usr/bin/env bash
# script to install load balancer HAproxy  1.5 or greater
sudo apt-get -y update && sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i "\$ a\listen 58030-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserver 58030-web-01 54.196.36.204:80 check\n\tserver 58030-web-02 54.237.90.27:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
