#!/usr/bin/env bash
# script to display "To infinity and beyond" infinitely with sleep 2. Print "I am invincible!!!" when recieved SIGTERM signal

echo "$$" > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "rm /var/run/myscript.pid; exit" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while true; do
      echo "To infinity and beyond"
      sleep 2
done
