#!/usr/bin/env bash
#
# Block all incoming traffic not except on port 22, 80, or 443

apt update
apt install -y ufw
ufw disable
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow https
ufw allow http
ufw enable
